# Paths
base_path: "/Users/renatacoppo/epochal/data-analysis/epochal"

# Number of initial simulation years to skip
skip_years: 1

# Number of years to load from each simulation
nyears: 100

# Reference experiment
reference: "x3"

# Plot directory
plot_directory: "plots"
comparison_plot_directory: "comparison_plots"

# Experiments
experiments:

  #pi:
  #  directory: "pix1"
  #  co2: 1

  #  atm: "processed/pix1_atm_annual_mean_1600-1799.nc"
  #  oce: "processed/pix1_oce_annual_mean_1600-1799.nc"
  #  moc: "processed/pix1_moc_annual_mean_1600-1799.nc"

  #x1.1:
    #directory: "oix1"
    #co2: 1
   #end_year: 1701 #Last complete year

    #atm: "processed/oix1_atm_annual_mean_1600-1799.nc"
    #oce: "processed/oix1_oce_annual_mean_1600-1799.nc"
    #moc: "processed/oix1_moc_annual_mean_1600-1799.nc"

  #x1.2:
    #directory: "eex1"
    #co2: 1
   #end_year: 1701 #Last complete year

    #atm: "processed/eex1_atm_annual_mean_1600-1649.nc"
    #oce: "processed/eex1_oce_annual_mean_1600-1649.nc"
    #moc: "processed/eex1_moc_annual_mean_1600-1649.nc"

  #x1.3:
    #directory: "tex1"
    #co2: 1
   #end_year: 1701 #Last complete year

    #atm: "processed/tex1_atm_annual_mean_1600-1650.nc"
    #oce: "processed/tex1_oce_annual_mean_1600-1650.nc"
    #moc: "processed/tex1_moc_annual_mean_1600-1650.nc"

  #x1.4:
    #directory: "xex1"
    #co2: 1
   #end_year: 1701 #Last complete year

    #atm: "processed/xex1_atm_annual_mean_1600-1649.nc"
    #oce: "processed/xex1_oce_annual_mean_1600-1649.nc"
    #moc: "processed/xex1_moc_annual_mean_1600-1649.nc"

  #x1.5:
    #directory: "vex1"
    #co2: 1
   #end_year: 1701 #Last complete year

    #atm: "processed/vex1_atm_annual_mean_1600-1649.nc"
    #oce: "processed/vex1_oce_annual_mean_1600-1649.nc"
    #moc: "processed/vex1_moc_annual_mean_1600-1649.nc"

  #x1:
  #  directory: "pex1"
  #  co2: 1
    
  #  atm: "processed/atm_annual_mean_1600-1799.nc"
  #  oce: "processed/oce_annual_mean_1600-1799.nc"
  #  moc: "processed/moc_annual_mean_1600-1799.nc"

  # Optional experiments
  x3:
    directory: "nex3"
    co2: 3

    #end_year: 1805 #Last complete year
    atm: "processed/nex3_atm_annual_mean_1600-2099.nc"
    oce: "processed/nex3_oce_annual_mean_1600-2099.nc"
    moc: "processed/nex3_moc_annual_mean_1600-2099.nc"
    warm_fix: "nex3.log" #051

  x3.1:
    directory: "wex3"
    co2: 3

    #end_year: 1805 #Last complete year
    atm: "processed/wex3_atm_annual_mean_1600-1650.nc"
    oce: "processed/wex3_oce_annual_mean_1600-1650.nc"
    moc: "processed/wex3_moc_annual_mean_1600-1650.nc"
    warm_fix: "wex3.log" #051

  x3.2:
    directory: "lex3"
    co2: 3

    #end_year: 1805 #Last complete year
    atm: "processed/lex3_atm_annual_mean_1600-1649.nc"
    oce: "processed/lex3_oce_annual_mean_1600-1649.nc"
    moc: "processed/lex3_moc_annual_mean_1600-1649.nc"
    warm_fix: "lex3.log" #050

  x4:
    directory: "pex4"
    co2: 4

    #end_year: 1805 #Last complete year
    atm: "processed/pex4_atm_annual_mean_1600-1649.nc"
    oce: "processed/pex4_oce_annual_mean_1600-1649.nc"
    moc: "processed/pex4_moc_annual_mean_1600-1649.nc"
    warm_fix: "pex4.log" #050

  x6:
    directory: "pex6"
    co2: 6
    end_year: 1701 #Last complete year

    atm: "processed/pex6_atm_annual_mean_1600-1702.nc"
    oce: "processed/pex6_oce_annual_mean_1600-1702.nc"
    moc: "processed/pex6_moc_annual_mean_1600-1702.nc"
    warm_fix: "pex6.log" #052


deepmip:

    CESM:
      tas:
        pi: "DeepMIP/CESM1.2_CAM5-piControl-tas-v1.0.mean_um_2020-11-19.nc"
        1x: "DeepMIP/CESM1.2_CAM5-deepmip_sens_1xCO2-tas-v1.0.mean_um_2020-11-19.nc"
        3x: "DeepMIP/CESM1.2_CAM5-deepmip_stand_3xCO2-tas-v1.0.mean_um_2020-11-19.nc"
        6x: "DeepMIP/CESM1.2_CAM5-deepmip_stand_6xCO2-tas-v1.0.mean_um_2020-11-19.nc"
        9x: "DeepMIP/CESM1.2_CAM5-deepmip_sens_9xCO2-tas-v1.0.mean_um_2020-11-19.nc"

      sst:
        pi:  "DeepMIP/CESM1.2_CAM5-piControl-tos-v1.0.mean_um_sst_nn_2020-11-19.nc"
        1x:  "DeepMIP/CESM1.2_CAM5-deepmip_sens_1xCO2-tos-v1.0.mean_um_sst_nn_2020-11-19.nc"
        3x:  "DeepMIP/CESM1.2_CAM5-deepmip_stand_3xCO2-tos-v1.0.mean_um_sst_nn_2020-11-19.nc"
        6x:  "DeepMIP/CESM1.2_CAM5-deepmip_stand_6xCO2-tos-v1.0.mean_um_sst_nn_2020-11-19.nc"
        9x:  "DeepMIP/CESM1.2_CAM5-deepmip_sens_9xCO2-tos-v1.0.mean_um_sst_nn_2020-11-19.nc"

    COSMOS:
      tas:
        pi: "DeepMIP/COSMOS-landveg_r2413-piControl-tas-v1.0.mean_um_2020-11-19.nc"
        1x: "DeepMIP/COSMOS-landveg_r2413-deepmip_sens_1xCO2-tas-v1.0.mean_um_2020-11-19.nc"
        3x: "DeepMIP/COSMOS-landveg_r2413-deepmip_stand_3xCO2-tas-v1.0.mean_um_2020-11-19.nc"
        4x: "DeepMIP/COSMOS-landveg_r2413-deepmip_sens_4xCO2-tas-v1.0.mean_um_2020-11-19.nc"

      sst:
        pi:  "DeepMIP/COSMOS-landveg_r2413-piControl-tos-v1.0.mean_um_sst_nn_2020-11-19.nc"
        1x:  "DeepMIP/COSMOS-landveg_r2413-deepmip_sens_1xCO2-tos-v1.0.mean_um_sst_nn_2020-11-19.nc"
        3x:  "DeepMIP/COSMOS-landveg_r2413-deepmip_stand_3xCO2-tos-v1.0.mean_um_sst_nn_2020-11-19.nc"
        4x:  "DeepMIP/COSMOS-landveg_r2413-deepmip_sens_4xCO2-tos-v1.0.mean_um_sst_nn_2020-11-19.nc"


    GFDL:
      tas:
        pi: "DeepMIP/GFDL_CM2.1-piControl-tas-v1.0.mean_um_2020-11-19.nc"
        1x: "DeepMIP/GFDL_CM2.1-deepmip_sens_1xCO2-tas-v1.0.mean_um_2020-11-19.nc"
        2x: "DeepMIP/GFDL_CM2.1-deepmip_sens_2xCO2-tas-v1.0.mean_um_2020-11-19.nc"
        3x: "DeepMIP/GFDL_CM2.1-deepmip_stand_3xCO2-tas-v1.0.mean_um_2020-11-19.nc"
        4x: "DeepMIP/GFDL_CM2.1-deepmip_sens_4xCO2-tas-v1.0.mean_um_2020-11-19.nc"
        6x: "DeepMIP/GFDL_CM2.1-deepmip_stand_6xCO2-tas-v1.0.mean_um_2020-11-19.nc"

      sst:
        pi:  "DeepMIP/GFDL_CM2.1-piControl-tos-v1.0.mean_um_sst_nn_2020-11-19.nc"
        1x:  "DeepMIP/GFDL_CM2.1-deepmip_sens_1xCO2-tos-v1.0.mean_um_sst_nn_2020-11-19.nc"
        2x:  "DeepMIP/GFDL_CM2.1-deepmip_sens_2xCO2-tos-v1.0.mean_um_sst_nn_2020-11-19.nc"
        3x:  "DeepMIP/GFDL_CM2.1-deepmip_stand_3xCO2-tos-v1.0.mean_um_sst_nn_2020-11-19.nc"
        4x:  "DeepMIP/GFDL_CM2.1-deepmip_sens_4xCO2-tos-v1.0.mean_um_sst_nn_2020-11-19.nc"
        6x:  "DeepMIP/GFDL_CM2.1-deepmip_stand_6xCO2-tos-v1.0.mean_um_sst_nn_2020-11-19.nc"

    HadCM:
      tas:
        pi: "DeepMIP/HadCM3B_M2.1aN-piControl-tas-v1.0.mean_um_2020-11-19.nc"
        1x: "DeepMIP/HadCM3B_M2.1aN-deepmip_sens_1xCO2-tas-v1.0.mean_um_2020-11-19.nc"
        2x: "DeepMIP/HadCM3B_M2.1aN-deepmip_sens_2xCO2-tas-v1.0.mean_um_2020-11-19.nc"
        3x: "DeepMIP/HadCM3B_M2.1aN-deepmip_stand_3xCO2-tas-v1.0.mean_um_2020-11-19.nc"

      sst:
        pi: "DeepMIP/HadCM3B_M2.1aN-piControl-tos-v1.0.mean_um_sst_nn_2020-11-19.nc"
        1x: "DeepMIP/HadCM3B_M2.1aN-deepmip_sens_1xCO2-tos-v1.0.mean_um_sst_nn_2020-11-19.nc"
        2x: "DeepMIP/HadCM3B_M2.1aN-deepmip_sens_2xCO2-tos-v1.0.mean_um_sst_nn_2020-11-19.nc"
        3x: "DeepMIP/HadCM3B_M2.1aN-deepmip_stand_3xCO2-tos-v1.0.mean_um_sst_nn_2020-11-19.nc"

    INM:
      tas:
        pi: "DeepMIP/INM-CM4-8-piControl-tas-v1.0.mean_um_2020-11-19.nc"
        6x: "DeepMIP/INM-CM4-8-deepmip_stand_6xCO2-tas-v1.0.mean_um_2020-11-19.nc"

      sst:
        pi: "DeepMIP/INM-CM4-8-piControl-tos-v1.0.mean_um_sst_nn_2020-11-19.nc"
        6x: "DeepMIP/INM-CM4-8-deepmip_stand_6xCO2-tos-v1.0.mean_um_sst_nn_2020-11-19.nc"

    IPSL:
      tas:
        pi: "DeepMIP/IPSLCM5A2-piControl-tas-v1.0.mean_um_2020-11-19.nc"
        1.5x: "DeepMIP/IPSLCM5A2-deepmip_sens_1.5xCO2-tas-v1.0.mean_um_2020-11-19.nc"
        3x: "DeepMIP/IPSLCM5A2-deepmip_stand_3xCO2-tas-v1.0.mean_um_2020-11-19.nc"

      sst:
        pi: "DeepMIP/IPSLCM5A2-piControl-tos-v1.0.mean_um_sst_nn_2020-11-19.nc"
        1.5x: "DeepMIP/IPSLCM5A2-deepmip_sens_1.5xCO2-tos-v1.0.mean_um_sst_nn_2020-11-19.nc"
        3x: "DeepMIP/IPSLCM5A2-deepmip_stand_3xCO2-tos-v1.0.mean_um_sst_nn_2020-11-19.nc"

    MIROC:
      tas:
        pi: "DeepMIP/MIROC4m-piControl-tas-v1.0.mean_um_2020-11-19.nc"
        3x: "DeepMIP/MIROC4m-deepmip_stand_3xCO2-tas-v1.0.mean_um_2020-11-19.nc"

      sst:
        pi: "DeepMIP/MIROC4m-piControl-tos-v1.0.mean_um_sst_nn_2020-11-19.nc"
        3x: "DeepMIP/MIROC4m-deepmip_stand_3xCO2-tos-v1.0.mean_um_sst_nn_2020-11-19.nc"

    NorESM:
      tas:
        pi: "DeepMIP/NorESM1_F-piControl-tas-v1.0.mean_um_2020-11-19.nc"
        2x: "DeepMIP/NorESM1_F-deepmip_sens_2xCO2-tas-v1.0.mean_um_2020-11-19.nc"
        4x: "DeepMIP/NorESM1_F-deepmip_sens_4xCO2-tas-v1.0.mean_um_2020-11-19.nc"

      sst:
        pi: "DeepMIP/NorESM1_F-piControl-tos-v1.0.mean_um_sst_nn_2020-11-19.nc"
        2x: "DeepMIP/NorESM1_F-deepmip_sens_2xCO2-tos-v1.0.mean_um_sst_nn_2020-11-19.nc"
        4x: "DeepMIP/NorESM1_F-deepmip_sens_4xCO2-tos-v1.0.mean_um_sst_nn_2020-11-19.nc"