cdo_path: /usr/local/apps/cdo/2.4.0/bin/cdo

base_output: /lus/h2resw01/hpcperm/ecme3497/data-analysis/epochal/ # output folder

experiments:
  PV20: /lus/h2resw01/scratch/ecme3497/ece4/PV20/output/ # input folder

variables:
  atmosphere: tas,pr,rsut,rlut,rsdt # for cdo
  ocean: tos,sos,zos,so,thetao # for cdo
  moc: ["msftyz"] # for xarray

filters: # for selecting the file type from the simulation output
  oce: "oce_1m_T"
  moc: "oce_1m_diaptr3d_"
  atm: "atm_cmip6_1m"
  atm_exclude: "_pl_"
